#define NUMBER_OF_PLAYERS 2

#define MAX_NUMBER_OF_UNITS_PER_PLAYER 20
#define MAX_NUMBER_OF_UNITS_PER_ZONE 10

#define ONE_WOUND_POINT 1
#define TWO_WOUND_POINTS 2

#define ARRAY_INCREMENT_SIZE 3

#define NUMBER_OF_SECTORS 3    // columns
#define NUMBER_OF_POSITIONS 5  // rows
